services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    container_name: example-web
    ports:
      - ${PORT:-8080}:${PORT:-8080}
    environment:
      - PRODUCTION=true
      - DB_URL=jdbc:mysql://db:5432/${DB_NAME:-example}
      - DB_USERNAME=${DB_USERNAME:-mysql}
      - DB_PASSWORD=${DB_PASSWORD:-mysql}
      - PORT=${PORT:-8080}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: example-db
    ports:
      - 3306:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=${DB_NAME:-example}
      - MYSQL_USER=${DB_USERNAME:-mysql}
      - MYSQL_PASSWORD=${DB_PASSWORD:-mysql}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    name: example-data
    external: true
