@param io.github.raniagus.project.view.NotFoundViewModel vm

@template.base(
title = @`Not Found`,
styles = @``,
body = @`
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1>404</h1>
                    <p>There's nothing here.</p>
                    <a href="/">Take me home</a>
                </div>
            </div>
        </div>
    </body>
`,
scripts = @``)
